### ISSUE TITLE
encoding incompatibility when running cursor.py

### ISSUE THREAD

**Issue by Hecmay** [rqlite/sqlalchemy-rqlite#5]
I am trying to use RQlite to replace Sqlite in my parallel computing project, and I encountered the encoding issue when running /pyrqlite/cursor.py:
```shell
Traceback (most recent call last):
  File "mmm_tuner.py", line 58, in <module>
    GccFlagsTuner.main(argparser.parse_args())
  File "/home/sx233/test/opentuner/opentuner/measurement/interface.py", line 291, in main
    return TuningRunMain(cls(args, *pargs, **kwargs), args).main()
  File "/home/sx233/test/opentuner/opentuner/tuningrunmain.py", line 194, in main
    self.init()
  File "/home/sx233/test/opentuner/opentuner/tuningrunmain.py", line 176, in init
    self.search_driver = self.search_driver_cls(**driver_kwargs)
  File "/home/sx233/test/opentuner/opentuner/search/driver.py", line 74, in __init__
    self.session.flush()
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/pyrqlite/cursors.py", line 114, in execute
    operation = self._substitute_params(operation, parameters)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/pyrqlite/cursors.py", line 102, in _substitute_params
    return ''.join(subst)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xda in position 2: ordinal not in range(128)
```

Similar error will occur when I set the default python encoding format to be "utf-8" 
`UnicodeDecodeError: 'utf8' codec can't decode byte 0xda in position 2: invalid continuation byte`

and Sqlalchemy fails to insert and rollback:
```shell
[     0s]    INFO sqlalchemy.engine.base.Engine: INSERT INTO tuning_run (uuid, program_version_id, machine_class_id, input_class_id, name, args, objective, state, start_date, end_date, final_config_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2017-09-11 10:14:32,577 INFO sqlalchemy.engine.base.Engine ('0d0a42787b78461a9b6ba19ba7199cf5', 1, None, None, 'unnamed', 'x\xdaMQ=o\xd4@\x10%!\xc7%\xbe|\x1fp\x04\x1aJ\x10\x12\t\x12U\xba\x90\xf2t\xae\x982Z\x8d\xd7s\xf6H\xeb\xf5\xce\xce\xba\xb8H\x91\xa0\xc3\xff\x97\x1f\xc0 ... (760 characters truncated) ... 91\xc5\xb2\x80"p\xc8B\x9e}#\xef\x96/`\xf1\xb0\x9d\x12F\xdb\x9a\xfb\xf7\x18\xe5[\x92\xb3\x11f\xcf\xf6\x96\xf7%L}o\xea!\xa8|\x18\x87\xea\xeb?\xf1,\xac(', '\x80\x02copentuner.search.objective\nMinimizeTime\nq\x01)\x81q\x02}q\x03U\x06driverq\x04Nsb.', 'QUEUED', '2017-09-11 10:14:32.559986', None, None)
[     0s]    INFO sqlalchemy.engine.base.Engine: ('0d0a42787b78461a9b6ba19ba7199cf5', 1, None, None, 'unnamed', 'x\xdaMQ=o\xd4@\x10%!\xc7%\xbe|\x1fp\x04\x1aJ\x10\x12\t\x12U\xba\x90\xf2t\xae\x982Z\x8d\xd7s\xf6H\xeb\xf5\xce\xce\xba\xb8H\x91\xa0\xc3\xff\x97\x1f\xc0 ... (760 characters truncated) ... 91\xc5\xb2\x80"p\xc8B\x9e}#\xef\x96/`\xf1\xb0\x9d\x12F\xdb\x9a\xfb\xf7\x18\xe5[\x92\xb3\x11f\xcf\xf6\x96\xf7%L}o\xea!\xa8|\x18\x87\xea\xeb?\xf1,\xac(', '\x80\x02copentuner.search.objective\nMinimizeTime\nq\x01)\x81q\x02}q\x03U\x06driverq\x04Nsb.', 'QUEUED', '2017-09-11 10:14:32.559986', None, None)
2017-09-11 10:14:32,578 INFO sqlalchemy.engine.base.Engine ROLLBACK
[     0s]    INFO sqlalchemy.engine.base.Engine: ROLLBACK`
```

**Comment by zmedico** [comment]
Could you create a minimal test case to reproduce the issue?

**Comment by Hecmay** [comment]
Yes. Please directly run the encoding_case.py to reproduce the issue.

 I think the issue might be caused by incompatibility with the "PickleType" in Sqlalchemy like:
   
    class TuningRun(Base):  
      args = Column(PickleType(pickler=CompressedPickler))

**Comment by zmedico** [comment]
Minimal test case, works with `sqlite://`:
```python
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from sqlalchemy.orm import Session
from sqlalchemy import Column, Integer, PickleType
from sqlalchemy.dialects import registry

Base = declarative_base()

class Object(Base):
    __tablename__ = 'object'
    sample_id = Column(Integer, primary_key=True)
    obj = Column(PickleType())

registry.register("rqlite.pyrqlite", "sqlalchemy_rqlite.pyrqlite", "dialect")

database = 'rqlite+pyrqlite://localhost:4001'
#database = 'sqlite://'

engine = create_engine(database, echo=True)
Base.metadata.create_all(engine)
session = Session(engine)

session.add(Object(obj='foo'))
session.flush()

```

**Comment by zmedico** [comment]
I patched pyrqlite as follows:
```diff
diff --git a/src/pyrqlite/extensions.py b/src/pyrqlite/extensions.py
index fc4ffc5..87b20bd 100644
--- a/src/pyrqlite/extensions.py
+++ b/src/pyrqlite/extensions.py
@@ -72,7 +72,7 @@ def _null_wrapper(converter, value):
 
 
 adapters = {
-    bytes: lambda x: x.decode('utf-8'),
+    bytes: lambda x: codecs.encode(x, 'base64').decode('utf-8'),
     float: lambda x: x,
     int: lambda x: x,
     bool: int,
@@ -92,7 +92,7 @@ converters = {
     'FLOAT': functools.partial(_null_wrapper, float),
     'REAL': functools.partial(_null_wrapper, float),
     'NULL': lambda x: None,
-    'BLOB': lambda x: x,
+    'BLOB': lambda x: codecs.decode(x, 'base64'),
     'DATE': functools.partial(_null_wrapper, _convert_date),
     'TIMESTAMP': functools.partial(_null_wrapper, _convert_timestamp),
 }
@@ -159,7 +159,7 @@ def _convert_to_python(column_name, type_, parse_decltypes=False, parse_colnames
 
 
 def _adapt_from_python(value):
-    if not isinstance(value, basestring):
+    if not isinstance(value, unicode):
         adapter_key = (type(value), sqlite3.PrepareProtocol)
         adapter = adapters.get(adapter_key)
         try:
```
This causes it to emit an insert statement like `INSERT INTO object (obj) VALUES ('gAJVA2Zvb3EBLg==\n')` which corresponds to the base64 encoded pickle of `'foo'`. When selecting that row from v4.1.0, it comes back as:
```json
{
  "results": [
    {
      "values": [
        [
          1,
          "Z0FKVkEyWnZiM0VCTGc9PQo="
        ]
      ],
      "types": [
        "integer",
        "blob"
      ],
      "columns": [
        "object_obj_id",
        "object_obj"
      ]
    }
  ]
}
```
Here, `Z0FKVkEyWnZiM0VCTGc9PQo=` is the base64 encoding of `gAJVA2Zvb3EBLg==\n`, so it's encoded in base64 twice. @otoolep, is this double base64 encoding a bug? I would have expected it to return `gAJVA2Zvb3EBLg==\n` instead. A dump of the database from `localhost:4001/db/backup` looks like this:
```sql
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE object (
	obj_id INTEGER NOT NULL, 
	obj BLOB, 
	PRIMARY KEY (obj_id)
);
INSERT INTO object VALUES(1,replace('gAJVA2Zvb3EBLg==\n','\n',char(10)));
COMMIT;
```

**Comment by otoolep** [comment]
Is this the same issue as https://github.com/rqlite/rqlite/issues/265 ?
Maybe it's time to fix it. :-)

**Comment by zmedico** [comment]
Until we've added binary data support to rqlite, people might use something like this as a substitute for PickleType, so that rqlite will simply treat the data as base64 text:
```python
from sqlalchemy.types import NVARCHAR, TypeDecorator

class Base64PickleType(TypeDecorator):

    impl = NVARCHAR

    def process_bind_param(self, value, dialect):
        if value is not None:
            value = codecs.encode(pickle.dumps(value),
                'base64').decode('utf-8')
        return value

    def process_result_value(self, value, dialect):
        if value is not None:
            return pickle.loads(codecs.decode(
                value.encode('utf-8'), 'base64'))
        return value
```

**Comment by Hecmay** [comment]
Thanks!  this works in my case.

But I will have another error when querying info from the database. it seems that base64_codec.py is trying to decode a str in date format like "2017-09-16T12:38:47.494266Z"


```shell
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    session.query(Object, Object.obj_id).all()
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/pyrqlite/cursors.py", line 183, in execute
    else converter(value))))
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/site-packages/pyrqlite/extensions.py", line 209, in _conditional_string_decode_base64
    value = codecs.decode(value, 'base64')
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/home/sx233/datuner/releases/Linux_x86_64/install/lib/python2.7/base64.py", line 322, in decodestring
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```


please see the minimal test case:
```python
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from sqlalchemy.orm import Session
from sqlalchemy import Column, Integer, PickleType, DateTime
from sqlalchemy.dialects import registry
import codecs
import pickle
from datetime import datetime
from sqlalchemy.types import NVARCHAR, TypeDecorator

class Base64PickleType(TypeDecorator):
  impl = NVARCHAR
  def process_bind_param(self, value, dialect):
    if value is not None:
      value = codecs.encode(pickle.dumps(value),
              'base64').decode('utf-8')
    return value

  def process_result_value(self, value, dialect):
    if value is not None:
      return pickle.loads(codecs.decode(
             value.encode('utf-8'), 'base64'))
      return value

Base = declarative_base()

class Object(Base):
    __tablename__ = 'object'
    obj_id = Column(Integer, primary_key=True)
    obj = Column(Base64PickleType())
    date = Column(DateTime)

registry.register("rqlite.pyrqlite", "sqlalchemy_rqlite.pyrqlite", "dialect")
database = 'rqlite+pyrqlite://localhost:4001'
#database = 'sqlite://'

engine = create_engine(database, echo=True)
Base.metadata.create_all(engine)
session = Session(engine)
session.add(Object(obj='foo',date=datetime.now()))
session.flush()
session.query(Object, Object.date).all()
```

**Comment by zmedico** [comment]
This should fix the DateTime issue:

https://github.com/rqlite/pyrqlite/commit/c170d023ef1261843f0148f89e16311b9f449188

**Comment by zmedico** [comment]
https://github.com/rqlite/pyrqlite/commit/1f45e8acf3212433fe9adb88b4fe5d13a9a48be8 solves the binary data problem by sending [BLOB literals containing hexadecimal data](https://sqlite.org/lang_expr.html#hexint) to rqlite.
